import { test, expect, closeApiDialog, closeBookIdeaDialog, reactClick } from './fixtures'

test.describe('角色管理', () => {
  test.beforeEach(async ({ window }) => {
    await closeApiDialog(window)
    await closeBookIdeaDialog(window)
  })

  test('切换到角色视图', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const searchInput = window.locator('input[placeholder="搜索角色..."]')
    await expect(searchInput).toBeVisible()
  })

  test('空状态提示', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const emptyHint = window.getByText('暂无角色，点击 + 添加')
    await expect(emptyHint).toBeVisible()
  })

  test('新建角色卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    await expect(dialog).toBeVisible()
    const dialogTitle = window.getByText('新建角色')
    await expect(dialogTitle).toBeVisible()
    const nameInput = dialog.locator('input[placeholder="角色名"]')
    await nameInput.fill('林黛玉')
    await window.waitForTimeout(200)
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const characterCard = window.getByText('林黛玉')
    await expect(characterCard).toBeVisible()
  })

  test('角色列表显示', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="角色名"]')
    await nameInput.fill('贾宝玉')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const characterCard = window.getByText('贾宝玉')
    await expect(characterCard).toBeVisible()
  })

  test('编辑角色卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    let dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="角色名"]')
    await nameInput.fill('薛宝钗')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const characterCard = window.getByText('薛宝钗')
    await characterCard.click()
    await window.waitForTimeout(500)
    dialog = window.locator('[role="dialog"][data-state="open"]')
    await expect(dialog).toBeVisible()
    const editTitle = window.getByText('编辑角色')
    await expect(editTitle).toBeVisible()
  })

  test('搜索角色', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="角色名"]')
    await nameInput.fill('王熙凤')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const searchInput = window.locator('input[placeholder="搜索角色..."]')
    await searchInput.fill('王熙凤')
    await window.waitForTimeout(300)
    const result = window.getByText('王熙凤')
    await expect(result).toBeVisible()
    await searchInput.fill('不存在的角色')
    await window.waitForTimeout(300)
    const noResult = window.getByText('未找到匹配角色')
    await expect(noResult).toBeVisible()
  })

  test('删除角色卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="角色"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="角色名"]')
    await nameInput.fill('刘姥姥')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const characterCard = window.locator('.border-r .rounded.border:has-text("刘姥姥")')
    await characterCard.click({ button: 'right' })
    await window.waitForTimeout(300)
    const deleteBtn = window.locator('.fixed.z-50 button:has-text("删除")')
    await expect(deleteBtn).toBeVisible()
    await deleteBtn.click()
    await window.waitForTimeout(500)
    const emptyHint = window.getByText('暂无角色，点击 + 添加')
    await expect(emptyHint).toBeVisible()
  })
})
