import { test, expect, closeApiDialog, closeBookIdeaDialog, reactClick } from './fixtures'

test.describe('世界观管理', () => {
  test.beforeEach(async ({ window }) => {
    await closeApiDialog(window)
    await closeBookIdeaDialog(window)
  })

  test('切换到世界观视图', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const searchInput = window.locator('input[placeholder="搜索设定..."]')
    await expect(searchInput).toBeVisible()
  })

  test('空状态提示', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const emptyHint = window.getByText('暂无设定，点击 + 添加')
    await expect(emptyHint).toBeVisible()
  })

  test('新建世界观卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    await expect(dialog).toBeVisible()
    const dialogTitle = window.getByText('新建设定')
    await expect(dialogTitle).toBeVisible()
    const nameInput = dialog.locator('input[placeholder="设定名称"]')
    await nameInput.fill('灵气体系')
    await window.waitForTimeout(200)
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const card = window.getByText('灵气体系')
    await expect(card).toBeVisible()
  })

  test('世界观卡列表', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    let dialog = window.locator('[role="dialog"][data-state="open"]')
    let nameInput = dialog.locator('input[placeholder="设定名称"]')
    await nameInput.fill('天机阁')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const card = window.getByText('天机阁')
    await expect(card).toBeVisible()
  })

  test('按类型筛选', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="设定名称"]')
    await nameInput.fill('昆仑山')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const locationFilter = window.locator('.border-r button:has-text("地点")')
    await expect(locationFilter).toBeVisible()
    await locationFilter.click()
    await window.waitForTimeout(300)
    const filteredCard = window.getByText('昆仑山')
    await expect(filteredCard).toBeVisible()
  })

  test('搜索世界观卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="设定名称"]')
    await nameInput.fill('剑道法则')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const searchInput = window.locator('input[placeholder="搜索设定..."]')
    await searchInput.fill('剑道')
    await window.waitForTimeout(300)
    const result = window.getByText('剑道法则')
    await expect(result).toBeVisible()
    await searchInput.fill('不存在的设定')
    await window.waitForTimeout(300)
    const noResult = window.getByText('未找到匹配设定')
    await expect(noResult).toBeVisible()
  })

  test('删除世界观卡', async ({ window }) => {
    await reactClick(window, '.border-r button[title="世界观"]')
    await window.waitForTimeout(300)
    const addBtn = window.locator('.border-r button:has(svg.lucide-plus)')
    await addBtn.click()
    await window.waitForTimeout(500)
    const dialog = window.locator('[role="dialog"][data-state="open"]')
    const nameInput = dialog.locator('input[placeholder="设定名称"]')
    await nameInput.fill('旧世界')
    const saveBtn = dialog.locator('button:has-text("保存")')
    await saveBtn.click()
    await window.waitForTimeout(500)
    const card = window.locator('.border-r .rounded.border:has-text("旧世界")')
    await card.click({ button: 'right' })
    await window.waitForTimeout(300)
    const deleteBtn = window.locator('.fixed.z-50 button:has-text("删除")')
    await expect(deleteBtn).toBeVisible()
    await deleteBtn.click()
    await window.waitForTimeout(500)
    const emptyHint = window.getByText('暂无设定，点击 + 添加')
    await expect(emptyHint).toBeVisible()
  })
})
